#!/usr/bin/env python3
# Copyright 2025-2026 ExoSpaceLabs
# SPDX-License-Identifier: Apache-2.0

"""Generate independent CCSDS Space Packet golden vectors for the v1.2 tests.

This script intentionally has no dependency on CCSDSPack. It implements only
primary-header packing and CRC-16/CCITT-FALSE calculation needed by the fixed
resources consumed by CCSDSPack_tester.
"""

from __future__ import annotations

import argparse
from pathlib import Path


def crc16_ccitt_false(data: bytes) -> int:
    crc = 0xFFFF
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            if crc & 0x8000:
                crc = ((crc << 1) ^ 0x1021) & 0xFFFF
            else:
                crc = (crc << 1) & 0xFFFF
    return crc


def encode_packet(
    *,
    version: int = 0,
    packet_type: int = 0,
    secondary_header_flag: int = 0,
    apid: int = 0,
    sequence_flags: int = 3,
    sequence_count: int = 0,
    secondary_header: bytes = b"",
    application_data: bytes = b"",
    crc16: bool = True,
) -> bytes:
    if not 0 <= version <= 0x7:
        raise ValueError("version must fit in 3 bits")
    if packet_type not in (0, 1):
        raise ValueError("packet_type must fit in 1 bit")
    if secondary_header_flag not in (0, 1):
        raise ValueError("secondary_header_flag must fit in 1 bit")
    if not 0 <= apid <= 0x7FF:
        raise ValueError("apid must fit in 11 bits")
    if not 0 <= sequence_flags <= 0x3:
        raise ValueError("sequence_flags must fit in 2 bits")
    if not 0 <= sequence_count <= 0x3FFF:
        raise ValueError("sequence_count must fit in 14 bits")

    packet_error_control_size = 2 if crc16 else 0
    packet_data_field_size = (
        len(secondary_header) + len(application_data) + packet_error_control_size
    )
    if not 1 <= packet_data_field_size <= 0x10000:
        raise ValueError("packet data field must contain between 1 and 65536 octets")

    identification = (
        (version << 13)
        | (packet_type << 12)
        | (secondary_header_flag << 11)
        | apid
    )
    sequence_control = (sequence_flags << 14) | sequence_count
    packet_data_length = packet_data_field_size - 1

    primary_header = (
        identification.to_bytes(2, "big")
        + sequence_control.to_bytes(2, "big")
        + packet_data_length.to_bytes(2, "big")
    )
    packet_without_error_control = primary_header + secondary_header + application_data

    if not crc16:
        return packet_without_error_control

    checksum = crc16_ccitt_false(packet_without_error_control)
    return packet_without_error_control + checksum.to_bytes(2, "big")


def write_hex(path: Path, data: bytes) -> None:
    path.write_text(
        "# Generated by test/reference/generate_ccsds_vectors.py. Do not edit.\n"
        + " ".join(f"{byte:02X}" for byte in data)
        + "\n",
        encoding="utf-8",
    )


def build_vectors() -> dict[str, bytes]:
    rollover_first = encode_packet(
        apid=1,
        sequence_count=0x3FFF,
        application_data=bytes([0xAA]),
    )
    rollover_second = encode_packet(
        apid=1,
        sequence_count=0,
        application_data=bytes([0xBB]),
    )

    return {
        "ccsds_golden_minimum_crc16.hex": encode_packet(),
        "ccsds_golden_no_secondary_crc16.hex": encode_packet(
            application_data=bytes([0xAA, 0x55])
        ),
        "ccsds_golden_custom_secondary_crc16.hex": encode_packet(
            secondary_header_flag=1,
            secondary_header=bytes([0x01, 0x02, 0x03]),
            application_data=bytes([0x04, 0x05]),
        ),
        "ccsds_golden_no_crc.hex": encode_packet(
            application_data=bytes([0xAA, 0x55]),
            crc16=False,
        ),
        "ccsds_golden_apid_0123_seq_0123_crc16.hex": encode_packet(
            packet_type=1,
            apid=0x123,
            sequence_count=0x123,
            application_data=bytes([0xDE, 0xAD]),
        ),
        "ccsds_golden_rollover_concat_crc16.hex": rollover_first + rollover_second,
    }


def main() -> None:
    default_output = Path(__file__).resolve().parents[1] / "test_resources"
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=default_output)
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    for filename, data in build_vectors().items():
        output = args.output_dir / filename
        write_hex(output, data)
        print(f"{output}: {len(data)} bytes")


if __name__ == "__main__":
    main()
