@startuml
title CCSDS::DataField UML Diagram
package [CCSDS] as C_0001131232607871793969 {
enum "ErrorCode" as C_0009441289820825074537
enum C_0009441289820825074537 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L29{ErrorCode}]] {
NONE
UNKNOWN_ERROR
NO_DATA
INVALID_DATA
INVALID_HEADER_DATA
INVALID_SECONDARY_HEADER_DATA
INVALID_APPLICATION_DATA
NULL_POINTER
INVALID_CHECKSUM
VALIDATION_FAILURE
TEMPLATE_SET_FAILURE
FILE_READ_ERROR
FILE_WRITE_ERROR
CONFIG_FILE_ERROR
}
class "Error" as C_0009567851690976834738
class C_0009567851690976834738 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L50{Error}]] {
+Error(const ErrorC...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L57{Error}]]]
..
+code() const : ErrorCode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L61{code}]]]
+message() const : const std::string & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L64{message}]]]
__
}
class "Result<T>" as C_0004081418331934384486
class C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L91{Result}]] {
+Result(T value) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L99{Result}]]]
+Result(Error error) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L105{Result}]]]
..
+error() const : Error [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L128{error}]]]
+has_value() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L108{has_value}]]]
+operator bool() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L131{operator bool}]]]
+value() : T & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L116{value}]]]
+value() const : const T & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L122{value}]]]
__
}
class "Result<bool>" as C_0014174674997599217076
class C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L39{Result}]] {
__
}
class "Result<std::vector<uint8_t>>" as C_0004629493886474321807
class C_0004629493886474321807 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L82{Result}]] {
__
}
abstract "SecondaryHeaderAbstract" as C_0017173607616216397172
abstract C_0017173607616216397172 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L53{SecondaryHeaderAbstract}]] {
+~SecondaryHeaderAbstract() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L56{~SecondaryHeaderAbstract}]]]
..
{abstract} +deserialize(const std::v...) = 0 : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L64{deserialize}]]]
{abstract} +getSize() const = 0 : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L77{getSize}]]]
{abstract} +getType() const = 0 : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L89{getType}]]]
+isPusHeader() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L92{isPusHeader}]]]
{abstract} +loadFromConfig(const Config...) = 0 : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L105{loadFromConfig}]]]
+matchesMissionProfile(const Missio...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L95{matchesMissionProfile}]]]
{abstract} +serialize() const = 0 : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L83{serialize}]]]
+setVariableLength(const bool b...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L112{setVariableLength}]]]
{abstract} +update(DataField * ...) = 0 : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L71{update}]]]
__
+variableLength : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L118{variableLength}]]]
}
class "BufferHeader" as C_0016881712599388925194
class C_0016881712599388925194 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L129{BufferHeader}]] {
+BufferHeader() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L132{BufferHeader}]]]
+BufferHeader(const std::v...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L138{BufferHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L145{deserialize}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L151{getSize}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L156{getType}]]]
+loadFromConfig(const Config...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L171{loadFromConfig}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L159{serialize}]]]
+update(DataField * ...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L165{update}]]]
__
}
class "SecondaryHeaderFactory" as C_0005588309261265651757
class C_0005588309261265651757 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L18{SecondaryHeaderFactory}]] {
+create(const std::s...) const : std::shared_ptr<SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L47{create}]]]
+registerCreator(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L34{registerCreator}]]]
+registerType<T>() : ResultBool
+typeIsRegistered(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L52{typeIsRegistered}]]]
__
}
enum "PacketErrorControlMode" as C_0001243513306714304585
enum C_0001243513306714304585 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L13{PacketErrorControlMode}]] {
None
CRC16
}
enum "PusRevision" as C_0001587312120908112732
enum C_0001587312120908112732 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L18{PusRevision}]] {
Unspecified
A
C
}
enum "PacketDirection" as C_0014770237610548259128
enum C_0014770237610548259128 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L24{PacketDirection}]] {
Unspecified
Telemetry
Telecommand
}
enum "TimeCodeFormat" as C_0000365949561418332127
enum C_0000365949561418332127 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L30{TimeCodeFormat}]] {
None
Cuc
Cds
}
class "MissionProfile" as C_0017357119726862570320
class C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L43{MissionProfile}]] {
__
+destinationIdOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L48{destinationIdOctets}]]]
+direction : PacketDirection [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L46{direction}]]]
+packetErrorControl : PacketErrorControlMode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L49{packetErrorControl}]]]
+pusATmPacketSubcounterPresent : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L53{pusATmPacketSubcounterPresent}]]]
+pusEnabled : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L44{pusEnabled}]]]
+pusRevision : PusRevision [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L45{pusRevision}]]]
+secondaryHeaderSpareOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L54{secondaryHeaderSpareOctets}]]]
+sourceIdOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L47{sourceIdOctets}]]]
+telemetryTimeCode : TimeCodeFormat [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L51{telemetryTimeCode}]]]
+telemetryTimeCodeOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L52{telemetryTimeCodeOctets}]]]
+telemetryTimestampPresent : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L50{telemetryTimestampPresent}]]]
}
class "PusSecondaryHeader" as C_0001098467024793841281
class C_0001098467024793841281 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L15{PusSecondaryHeader}]] {
#PusSecondaryHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L37{PusSecondaryHeader}]]]
..
{static} #appendIdentifier(std::vector<...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L42{appendIdentifier}]]]
+getDirection() const : PacketDirection [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L18{getDirection}]]]
+getMissionProfile() const : const MissionProfile & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L19{getMissionProfile}]]]
+getRevision() const : PusRevision [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L17{getRevision}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L20{getType}]]]
#identifierFits(std::uint32_...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L41{identifierFits}]]]
+isPusHeader() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L23{isPusHeader}]]]
+loadFromConfig(const Config...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L33{loadFromConfig}]]]
+matchesMissionProfile(const Missio...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L24{matchesMissionProfile}]]]
+matchesProfile(const Missio...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L27{matchesProfile}]]]
#profileIsValid() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L38{profileIsValid}]]]
{static} #readIdentifier(const std::v...) : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L44{readIdentifier}]]]
#trailingSpareIsZero(const std::v...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L46{trailingSpareIsZero}]]]
+update(DataField * ...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L30{update}]]]
__
#m_profile : MissionProfile [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L48{m_profile}]]]
}
class "PusTcSecondaryHeader" as C_0008871084556965139470
class C_0008871084556965139470 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L51{PusTcSecondaryHeader}]] {
#PusTcSecondaryHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L64{PusTcSecondaryHeader}]]]
..
#appendTcBody(std::vector<...) const : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L68{appendTcBody}]]]
+getAcknowledgementFlags() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L53{getAcknowledgementFlags}]]]
+getServiceSubtype() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L55{getServiceSubtype}]]]
+getServiceType() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L54{getServiceType}]]]
+getSourceId() const : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L56{getSourceId}]]]
#parseTcBody(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L69{parseTcBody}]]]
+setAcknowledgementFlags(std::uint8_t...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L58{setAcknowledgementFlags}]]]
+setServiceSubtype(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L60{setServiceSubtype}]]]
+setServiceType(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L59{setServiceType}]]]
+setSourceId(std::uint32_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L61{setSourceId}]]]
#tcSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L67{tcSize}]]]
__
#m_acknowledgementFlags : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L71{m_acknowledgementFlags}]]]
#m_serviceSubtype : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L73{m_serviceSubtype}]]]
#m_serviceType : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L72{m_serviceType}]]]
#m_sourceId : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L74{m_sourceId}]]]
}
class "PusTmSecondaryHeader" as C_0003796250724889769582
class C_0003796250724889769582 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L77{PusTmSecondaryHeader}]] {
#PusTmSecondaryHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L90{PusTmSecondaryHeader}]]]
..
#appendTmTail(std::vector<...) const : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L93{appendTmTail}]]]
+getDestinationId() const : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L81{getDestinationId}]]]
+getServiceSubtype() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L80{getServiceSubtype}]]]
+getServiceType() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L79{getServiceType}]]]
+getTimestamp() const : const std::vector<std::uint8_t> & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L82{getTimestamp}]]]
#parseTmTail(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L94{parseTmTail}]]]
+setDestinationId(std::uint32_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L86{setDestinationId}]]]
+setServiceSubtype(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L85{setServiceSubtype}]]]
+setServiceType(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L84{setServiceType}]]]
+setTimestamp(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L87{setTimestamp}]]]
#tmTailSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L95{tmTailSize}]]]
__
#m_destinationId : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L99{m_destinationId}]]]
#m_serviceSubtype : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L98{m_serviceSubtype}]]]
#m_serviceType : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L97{m_serviceType}]]]
#m_timestamp : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L100{m_timestamp}]]]
}
class "PusATcHeader" as C_0001473581857008901346
class C_0001473581857008901346 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L103{PusATcHeader}]] {
+PusATcHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L105{PusATcHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L109{deserialize}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L110{getSize}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L111{serialize}]]]
__
}
class "PusCTcHeader" as C_0004629837013344595315
class C_0004629837013344595315 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L114{PusCTcHeader}]] {
+PusCTcHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L116{PusCTcHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L120{deserialize}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L121{getSize}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L122{serialize}]]]
__
}
class "PusATmHeader" as C_0006271565114106479817
class C_0006271565114106479817 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L125{PusATmHeader}]] {
+PusATmHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L127{PusATmHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L134{deserialize}]]]
+getPacketSubcounter() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L132{getPacketSubcounter}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L135{getSize}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L136{serialize}]]]
+setPacketSubcounter(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L133{setPacketSubcounter}]]]
__
}
class "PusCTmHeader" as C_0000950279713321375027
class C_0000950279713321375027 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L142{PusCTmHeader}]] {
+PusCTmHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L144{PusCTmHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L155{deserialize}]]]
+getMessageTypeCounter() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L151{getMessageTypeCounter}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L156{getSize}]]]
+getTimeReferenceStatus() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L152{getTimeReferenceStatus}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L157{serialize}]]]
+setMessageTypeCounter(std::uint16_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L153{setMessageTypeCounter}]]]
+setTimeReferenceStatus(std::uint8_t...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L154{setTimeReferenceStatus}]]]
__
}
class "Result<std::shared_ptr<CCSDS::SecondaryHeaderAbstract>>" as C_0001094226650605249342
class C_0001094226650605249342 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L16{Result}]] {
__
}
class "PusSecondaryHeaderFactory" as C_0016695687058631780890
class C_0016695687058631780890 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L14{PusSecondaryHeaderFactory}]] {
+create(PusRevision ...) const : CCSDS::Result<std::shared_ptr<SecondaryHeaderAbstract>> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L16{create}]]]
+create(const std::s...) const : CCSDS::Result<std::shared_ptr<SecondaryHeaderAbstract>> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L18{create}]]]
{static} +isPusSelector(const std::s...) : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L21{isPusSelector}]]]
+typeIsSupported(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L20{typeIsSupported}]]]
__
}
class "DataField" as C_0009576894308489276275
class C_0009576894308489276275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L39{DataField}]] {
+DataField() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L46{DataField}]]]
+~DataField() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L49{~DataField}]]]
..
+RegisterSecondaryHeader<T>() : ResultBool
+getApplicationData() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L194{getApplicationData}]]]
+getApplicationData() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L192{getApplicationData}]]]
+getApplicationDataBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L172{getApplicationDataBytesSize}]]]
+getDataFieldAbsoluteBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L169{getDataFieldAbsoluteBytesSize}]]]
+getDataFieldAvailableBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L178{getDataFieldAvailableBytesSize}]]]
+getDataFieldHeader() : SecondaryHeaderAbstract & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L148{getDataFieldHeader}]]]
+getDataFieldHeader() const : const SecondaryHeaderAbstract & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L153{getDataFieldHeader}]]]
+getDataFieldHeaderAutoUpdateStatus() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L197{getDataFieldHeaderAutoUpdateStatus}]]]
+getDataFieldHeaderBytes() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L183{getDataFieldHeaderBytes}]]]
+getDataFieldHeaderBytes() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L181{getDataFieldHeaderBytes}]]]
+getDataFieldHeaderFactory() : SecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L134{getDataFieldHeaderFactory}]]]
+getDataFieldHeaderFactory() const : const SecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L136{getDataFieldHeaderFactory}]]]
+getDataFieldHeaderFlag() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L200{getDataFieldHeaderFlag}]]]
+getDataFieldUsedBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L175{getDataFieldUsedBytesSize}]]]
+getMissionProfile() const : const MissionProfile & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L64{getMissionProfile}]]]
+getPusDataFieldHeaderFactory() const : const PusSecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L140{getPusDataFieldHeaderFactory}]]]
+getSecondaryHeader() : std::shared_ptr<SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L203{getSecondaryHeader}]]]
+getSecondaryHeader() const : std::shared_ptr<const SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L205{getSecondaryHeader}]]]
+serialize() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L189{serialize}]]]
+setApplicationData(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L79{setApplicationData}]]]
+setApplicationData(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L71{setApplicationData}]]]
+setDataFieldHeader(std::shared_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L131{setDataFieldHeader}]]]
+setDataFieldHeader(const Config...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L123{setDataFieldHeader}]]]
+setDataFieldHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L116{setDataFieldHeader}]]]
+setDataFieldHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L108{setDataFieldHeader}]]]
+setDataFieldHeader(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L98{setDataFieldHeader}]]]
+setDataFieldHeader(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L88{setDataFieldHeader}]]]
+setDataFieldHeaderAutoUpdateStatus(const bool e...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L166{setDataFieldHeaderAutoUpdateStatus}]]]
+setDataPacketSize(const std::u...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L160{setDataPacketSize}]]]
+setMissionProfile(const Missio...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L63{setMissionProfile}]]]
+update() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L211{update}]]]
__
}
class "Packet" as C_0009809857242509377472
class C_0009809857242509377472 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L214{Packet}]] {
__
}
}
class "Config" as C_0003888813716297410290
class C_0003888813716297410290 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L29{Config}]] {
+get<T>(const std::s...) const : CCSDS::Result<T>
+isKey(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L65{isKey}]]]
+load(const std::s...) : CCSDS::ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L39{load}]]]
__
}
C_0009567851690976834738 o-- C_0009441289820825074537 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L67{m_code}]] : -m_code
C_0004081418331934384486 o-- C_0009567851690976834738 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L92{data}]] : -data
C_0014174674997599217076 ..|> C_0004081418331934384486
C_0004629493886474321807 ..|> C_0004081418331934384486
C_0017173607616216397172 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L64{}]]
C_0017173607616216397172 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L64{}]]
C_0017173607616216397172 ..> C_0009576894308489276275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L71{}]]
C_0017173607616216397172 ..> C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L95{}]]
C_0017173607616216397172 ..> C_0003888813716297410290 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L105{}]]
C_0016881712599388925194 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L145{}]]
C_0016881712599388925194 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L145{}]]
C_0016881712599388925194 ..> C_0009576894308489276275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L165{}]]
C_0016881712599388925194 ..> C_0003888813716297410290 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L171{}]]
C_0017173607616216397172 <|-- C_0016881712599388925194
C_0005588309261265651757 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L34{}]]
C_0005588309261265651757 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L34{}]]
C_0005588309261265651757 ..> C_0017173607616216397172 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L47{}]]
C_0005588309261265651757 ..> C_0017173607616216397172 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L57{m_creators}]] : -m_creators
C_0017357119726862570320 o-- C_0001587312120908112732 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L45{pusRevision}]] : +pusRevision
C_0017357119726862570320 o-- C_0014770237610548259128 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L46{direction}]] : +direction
C_0017357119726862570320 o-- C_0001243513306714304585 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L49{packetErrorControl}]] : +packetErrorControl
C_0017357119726862570320 o-- C_0000365949561418332127 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L51{telemetryTimeCode}]] : +telemetryTimeCode
C_0001098467024793841281 ..> C_0001587312120908112732 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L17{}]]
C_0001098467024793841281 ..> C_0014770237610548259128 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L18{}]]
C_0001098467024793841281 ..> C_0009576894308489276275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L30{}]]
C_0001098467024793841281 ..> C_0003888813716297410290 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L33{}]]
C_0001098467024793841281 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L33{}]]
C_0001098467024793841281 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L33{}]]
C_0001098467024793841281 o-- C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L48{m_profile}]] : #m_profile
C_0017173607616216397172 <|-- C_0001098467024793841281
C_0008871084556965139470 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L58{}]]
C_0008871084556965139470 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L58{}]]
C_0008871084556965139470 ..> C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L64{}]]
C_0001098467024793841281 <|-- C_0008871084556965139470
C_0003796250724889769582 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L86{}]]
C_0003796250724889769582 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L86{}]]
C_0003796250724889769582 ..> C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L90{}]]
C_0001098467024793841281 <|-- C_0003796250724889769582
C_0001473581857008901346 ..> C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L105{}]]
C_0001473581857008901346 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L109{}]]
C_0001473581857008901346 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L109{}]]
C_0008871084556965139470 <|-- C_0001473581857008901346
C_0004629837013344595315 ..> C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L116{}]]
C_0004629837013344595315 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L120{}]]
C_0004629837013344595315 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L120{}]]
C_0008871084556965139470 <|-- C_0004629837013344595315
C_0006271565114106479817 ..> C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L127{}]]
C_0006271565114106479817 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L134{}]]
C_0006271565114106479817 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L134{}]]
C_0003796250724889769582 <|-- C_0006271565114106479817
C_0000950279713321375027 ..> C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L144{}]]
C_0000950279713321375027 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L154{}]]
C_0000950279713321375027 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L154{}]]
C_0003796250724889769582 <|-- C_0000950279713321375027
C_0001094226650605249342 ..|> C_0004081418331934384486
C_0016695687058631780890 ..> C_0001587312120908112732 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{}]]
C_0016695687058631780890 ..> C_0014770237610548259128 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{}]]
C_0016695687058631780890 ..> C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{}]]
C_0016695687058631780890 ..> C_0001094226650605249342 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L16{}]]
C_0016695687058631780890 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L16{}]]
C_0016695687058631780890 ..> C_0017173607616216397172 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L16{}]]
C_0009576894308489276275 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L63{}]]
C_0009576894308489276275 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L63{}]]
C_0009576894308489276275 ..> C_0003888813716297410290 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L123{}]]
C_0009576894308489276275 --> C_0017173607616216397172 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L217{m_secondaryHeader}]] : -m_secondaryHeader
C_0009576894308489276275 o-- C_0005588309261265651757 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L218{m_secondaryHeaderFactory}]] : -m_secondaryHeaderFactory
C_0009576894308489276275 o-- C_0016695687058631780890 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L219{m_pusSecondaryHeaderFactory}]] : -m_pusSecondaryHeaderFactory
C_0009576894308489276275 o-- C_0017357119726862570320 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L220{m_missionProfile}]] : -m_missionProfile
C_0009576894308489276275 <.. C_0009809857242509377472 : +<<friend>>
C_0003888813716297410290 ..> C_0014174674997599217076 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L39{}]]
C_0003888813716297410290 ..> C_0004081418331934384486 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L39{}]]
C_0003888813716297410290 ..> C_0004629493886474321807 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L82{}]]

'Generated with clang-uml, version 0.6.3-59-gdfa2271
'LLVM version Ubuntu clang version 17.0.6 (9ubuntu1)
@enduml
