@startuml
title ccsds::Manager UML Diagram
package [ccsds] as C_0015722493921447645547 {
enum "ErrorCode" as C_0009051388942408461891
enum C_0009051388942408461891 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L29{ErrorCode}]] {
NONE
UNKNOWN_ERROR
NO_DATA
INVALID_DATA
INVALID_HEADER_DATA
INVALID_SECONDARY_HEADER_DATA
INVALID_APPLICATION_DATA
NULL_POINTER
INVALID_CHECKSUM
VALIDATION_FAILURE
TEMPLATE_SET_FAILURE
FILE_READ_ERROR
FILE_WRITE_ERROR
CONFIG_FILE_ERROR
}
class "Error" as C_0017566881135794494958
class C_0017566881135794494958 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L50{Error}]] {
+Error(const ErrorC...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L57{Error}]]]
..
+code() const : ErrorCode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L61{code}]]]
+message() const : const std::string & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L64{message}]]]
__
}
class "Result<T>" as C_0008099319371458986879
class C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L91{Result}]] {
+Result(T value) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L99{Result}]]]
+Result(Error error) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L105{Result}]]]
..
+error() const : Error [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L128{error}]]]
+has_value() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L108{has_value}]]]
+operator bool() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L131{operator bool}]]]
+value() : T & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L116{value}]]]
+value() const : const T & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L122{value}]]]
__
}
enum "ESequenceFlag" as C_0002282814802499769197
enum C_0002282814802499769197 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L27{ESequenceFlag}]] {
CONTINUING_SEGMENT
FIRST_SEGMENT
LAST_SEGMENT
UNSEGMENTED
}
enum "EHeaderStatus" as C_0006565293471114675048
enum C_0006565293471114675048 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L42{EHeaderStatus}]] {
NORMAL
IDLE
INVALID
}
class "PrimaryHeader" as C_0011505254011848722045
class C_0011505254011848722045 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L56{PrimaryHeader}]] {
+PrimaryHeader(const std::u...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L75{PrimaryHeader}]]]
__
+APID : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L60{APID}]]]
+dataLength : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L63{dataLength}]]]
+secondaryHeaderFlag : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L59{secondaryHeaderFlag}]]]
+sequenceCount : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L62{sequenceCount}]]]
+sequenceFlags : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L61{sequenceFlags}]]]
+type : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L58{type}]]]
+versionNumber : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L57{versionNumber}]]]
}
class "Result<bool>" as C_0008186123745702387052
class C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L153{Result}]] {
__
}
class "Header" as C_0011294920384177675248
class C_0011294920384177675248 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L109{Header}]] {
+Header() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L112{Header}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L210{deserialize}]]]
+getAPID() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L121{getAPID}]]]
+getDataLength() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L127{getDataLength}]]]
+getFullHeader() const : std::uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L146{getFullHeader}]]]
+getFullHeader() : std::uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L144{getFullHeader}]]]
+getHeaderStatus() const : EHeaderStatus [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L129{getHeaderStatus}]]]
+getSecondaryHeaderFlag() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L119{getSecondaryHeaderFlag}]]]
+getSequenceCount() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L125{getSequenceCount}]]]
+getSequenceFlags() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L123{getSequenceFlags}]]]
+getType() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L117{getType}]]]
+getVersionNumber() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L115{getVersionNumber}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L138{serialize}]]]
+serialize() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L136{serialize}]]]
+setAPID(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L175{setAPID}]]]
+setData(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L203{setData}]]]
+setData(const Primar...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L217{setData}]]]
+setDataLength(const std::u...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L196{setDataLength}]]]
+setSecondaryHeaderFlag(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L167{setSecondaryHeaderFlag}]]]
+setSequenceCount(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L189{setSequenceCount}]]]
+setSequenceFlags(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L182{setSequenceFlags}]]]
+setType(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L160{setType}]]]
+setVersionNumber(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L153{setVersionNumber}]]]
__
}
class "Result<std::vector<uint8_t>>" as C_0016810538617857061367
class C_0016810538617857061367 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L86{Result}]] {
__
}
class "Config" as C_0018286355310635740643
class C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L32{Config}]] {
+get<T>(const std::s...) const : Result<T>
+isKey(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L69{isKey}]]]
+load(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L43{load}]]]
__
}
abstract "SecondaryHeaderAbstract" as C_0005445694194400424073
abstract C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L53{SecondaryHeaderAbstract}]] {
+~SecondaryHeaderAbstract() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L56{~SecondaryHeaderAbstract}]]]
..
{abstract} +deserialize(const std::v...) = 0 : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L64{deserialize}]]]
{abstract} +getSize() const = 0 : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L77{getSize}]]]
{abstract} +getType() const = 0 : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L89{getType}]]]
+isPusHeader() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L92{isPusHeader}]]]
{abstract} +loadFromConfig(const ccsds:...) = 0 : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L105{loadFromConfig}]]]
+matchesMissionProfile(const Missio...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L95{matchesMissionProfile}]]]
{abstract} +serialize() const = 0 : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L83{serialize}]]]
+setVariableLength(const bool b...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L112{setVariableLength}]]]
{abstract} +update(DataField * ...) = 0 : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L71{update}]]]
__
+variableLength : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L118{variableLength}]]]
}
class "BufferHeader" as C_0014736019873459950331
class C_0014736019873459950331 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L129{BufferHeader}]] {
+BufferHeader() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L132{BufferHeader}]]]
+BufferHeader(const std::v...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L138{BufferHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L145{deserialize}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L151{getSize}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L156{getType}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L171{loadFromConfig}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L159{serialize}]]]
+update(DataField * ...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L165{update}]]]
__
}
class "SecondaryHeaderFactory" as C_0009041847757797157790
class C_0009041847757797157790 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L18{SecondaryHeaderFactory}]] {
+create(const std::s...) const : std::shared_ptr<SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L47{create}]]]
+registerCreator(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L34{registerCreator}]]]
+registerType<T>() : ResultBool
+typeIsRegistered(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L52{typeIsRegistered}]]]
__
}
package [time] as C_0004898341130237538964 {
enum "Format" as C_0014027148995399468784
enum C_0014027148995399468784 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L19{Format}]] {
None
Cuc
}
enum "Epoch" as C_0011169860713497893350
enum C_0011169860713497893350 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L25{Epoch}]] {
Unspecified
Ccsds1958Tai
AgencyDefined
}
enum "PFieldMode" as C_0003117097434587954110
enum C_0003117097434587954110 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L32{PFieldMode}]] {
Implicit
Explicit
}
class "CucConfiguration" as C_0010465517018640617180
class C_0010465517018640617180 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L38{CucConfiguration}]] {
__
+coarseOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L41{coarseOctets}]]]
+epoch : Epoch [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L39{epoch}]]]
+fineOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L42{fineOctets}]]]
+pField : PFieldMode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L40{pField}]]]
}
class "CucTime" as C_0014692306963991656514
class C_0014692306963991656514 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L46{CucTime}]] {
+operator!=(const CucTim...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L53{operator!=}]]]
+operator==(const CucTim...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L50{operator==}]]]
__
+coarse : std::uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L47{coarse}]]]
+fine : std::uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L48{fine}]]]
}
}
enum "PacketErrorControlMode" as C_0011113483064328568240
enum C_0011113483064328568240 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L19{PacketErrorControlMode}]] {
None
CRC16
}
package [pus] as C_0008266245607909693776 {
enum "Revision" as C_0006294303417563364908
enum C_0006294303417563364908 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L26{Revision}]] {
Unspecified
A
C
}
enum "Direction" as C_0001829865898408684403
enum C_0001829865898408684403 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L33{Direction}]] {
Unspecified
Telemetry
Telecommand
}
class "SecondaryHeader" as C_0017820635191381806822
class C_0017820635191381806822 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L20{SecondaryHeader}]] {
#SecondaryHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L51{SecondaryHeader}]]]
..
{static} #appendIdentifier(std::vector<...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L56{appendIdentifier}]]]
+getDirection() const : Direction [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L25{getDirection}]]]
+getMissionProfile() const : const MissionProfile & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L27{getMissionProfile}]]]
+getRevision() const : Revision [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L23{getRevision}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L29{getType}]]]
#identifierFits(std::uint32_...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L55{identifierFits}]]]
+isPusHeader() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L33{isPusHeader}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L47{loadFromConfig}]]]
+matchesMissionProfile(const Missio...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L35{matchesMissionProfile}]]]
+matchesProfile(const Missio...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L39{matchesProfile}]]]
#profileIsValid() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L52{profileIsValid}]]]
{static} #readIdentifier(const std::v...) : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L58{readIdentifier}]]]
#trailingSpareIsZero(const std::v...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L60{trailingSpareIsZero}]]]
+update(DataField * ...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L43{update}]]]
__
#m_profile : MissionProfile [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L62{m_profile}]]]
}
class "TcSecondaryHeader" as C_0004810502936549036890
class C_0004810502936549036890 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L66{TcSecondaryHeader}]] {
#TcSecondaryHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L92{TcSecondaryHeader}]]]
..
#appendTcBody(std::vector<...) const : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L96{appendTcBody}]]]
+getAcknowledgementFlags() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L69{getAcknowledgementFlags}]]]
+getServiceSubtype() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L73{getServiceSubtype}]]]
+getServiceType() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L71{getServiceType}]]]
+getSourceId() const : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L75{getSourceId}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L88{loadFromConfig}]]]
#parseTcBody(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L97{parseTcBody}]]]
+setAcknowledgementFlags(std::uint8_t...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L78{setAcknowledgementFlags}]]]
+setServiceSubtype(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L82{setServiceSubtype}]]]
+setServiceType(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L80{setServiceType}]]]
+setSourceId(std::uint32_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L84{setSourceId}]]]
#tcSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L95{tcSize}]]]
__
#m_acknowledgementFlags : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L99{m_acknowledgementFlags}]]]
#m_serviceSubtype : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L101{m_serviceSubtype}]]]
#m_serviceType : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L100{m_serviceType}]]]
#m_sourceId : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L102{m_sourceId}]]]
}
class "TmSecondaryHeader" as C_0004398363156631507099
class C_0004398363156631507099 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L106{TmSecondaryHeader}]] {
#TmSecondaryHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L132{TmSecondaryHeader}]]]
..
#appendTmTail(std::vector<...) const : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L135{appendTmTail}]]]
+getDestinationId() const : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L113{getDestinationId}]]]
+getServiceSubtype() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L111{getServiceSubtype}]]]
+getServiceType() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L109{getServiceType}]]]
+getTimestamp() const : const time::CucTime & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L115{getTimestamp}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L128{loadFromConfig}]]]
#parseTmTail(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L136{parseTmTail}]]]
+setDestinationId(std::uint32_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L122{setDestinationId}]]]
+setServiceSubtype(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L120{setServiceSubtype}]]]
+setServiceType(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L118{setServiceType}]]]
+setTimestamp(const time::...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L124{setTimestamp}]]]
#tmTailSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L137{tmTailSize}]]]
__
#m_destinationId : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L141{m_destinationId}]]]
#m_serviceSubtype : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L140{m_serviceSubtype}]]]
#m_serviceType : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L139{m_serviceType}]]]
#m_timestamp : time::CucTime [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L142{m_timestamp}]]]
}
package [rev_a] as C_0009768887864433069962 {
class "TcHeader" as C_0001755478337597829079
class C_0001755478337597829079 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L147{TcHeader}]] {
+TcHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L150{TcHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L155{deserialize}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L157{getSize}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L159{serialize}]]]
__
}
class "TmHeader" as C_0017247575000911418816
class C_0017247575000911418816 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L185{TmHeader}]] {
+TmHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L188{TmHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L198{deserialize}]]]
+getPacketSubcounter() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L194{getPacketSubcounter}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L200{getSize}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L206{loadFromConfig}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L202{serialize}]]]
+setPacketSubcounter(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L196{setPacketSubcounter}]]]
__
}
}
package [rev_c] as C_0012782847369517139209 {
class "TcHeader" as C_0004296692240053397319
class C_0004296692240053397319 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L166{TcHeader}]] {
+TcHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L169{TcHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L174{deserialize}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L176{getSize}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L178{serialize}]]]
__
}
class "TmHeader" as C_0009041677057813291073
class C_0009041677057813291073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L216{TmHeader}]] {
+TmHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L219{TmHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L235{deserialize}]]]
+getMessageTypeCounter() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L227{getMessageTypeCounter}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L237{getSize}]]]
+getTimeReferenceStatus() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L229{getTimeReferenceStatus}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L243{loadFromConfig}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L239{serialize}]]]
+setMessageTypeCounter(std::uint16_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L231{setMessageTypeCounter}]]]
+setTimeReferenceStatus(std::uint8_t...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L233{setTimeReferenceStatus}]]]
__
}
}
class "SecondaryHeaderFactory" as C_0002158309051506416943
class C_0002158309051506416943 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L14{SecondaryHeaderFactory}]] {
+create(Revision rev...) const : ccsds::Result<std::shared_ptr<SecondaryHeaderAbstract>> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{create}]]]
+create(const std::s...) const : ccsds::Result<std::shared_ptr<SecondaryHeaderAbstract>> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L20{create}]]]
{static} +isPusSelector(const std::s...) : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L25{isPusSelector}]]]
+typeIsSupported(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L23{typeIsSupported}]]]
__
}
}
class "MissionProfile" as C_0013482125278780870275
class C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L47{MissionProfile}]] {
__
+destinationIdOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L52{destinationIdOctets}]]]
+direction : pus::Direction [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L50{direction}]]]
+packetErrorControl : PacketErrorControlMode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L53{packetErrorControl}]]]
+pusATmPacketSubcounterPresent : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L57{pusATmPacketSubcounterPresent}]]]
+pusEnabled : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L48{pusEnabled}]]]
+pusRevision : pus::Revision [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L49{pusRevision}]]]
+secondaryHeaderSpareOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L58{secondaryHeaderSpareOctets}]]]
+sourceIdOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L51{sourceIdOctets}]]]
+telemetryCuc : time::CucConfiguration [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L56{telemetryCuc}]]]
+telemetryTimeCode : time::Format [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L55{telemetryTimeCode}]]]
+telemetryTimestampPresent : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L54{telemetryTimestampPresent}]]]
}
class "Result<std::shared_ptr<ccsds::SecondaryHeaderAbstract>>" as C_0007514998099265917869
class C_0007514998099265917869 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{Result}]] {
__
}
class "DataField" as C_0003434639916644007055
class C_0003434639916644007055 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L39{DataField}]] {
+DataField() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L46{DataField}]]]
+~DataField() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L49{~DataField}]]]
..
+RegisterSecondaryHeader<T>() : ResultBool
+getApplicationData() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L186{getApplicationData}]]]
+getApplicationData() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L184{getApplicationData}]]]
+getApplicationDataBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L164{getApplicationDataBytesSize}]]]
+getDataFieldAbsoluteBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L161{getDataFieldAbsoluteBytesSize}]]]
+getDataFieldAvailableBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L170{getDataFieldAvailableBytesSize}]]]
+getDataFieldUsedBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L167{getDataFieldUsedBytesSize}]]]
+getMissionProfile() const : const MissionProfile & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L64{getMissionProfile}]]]
+getPusSecondaryHeaderFactory() const : const pus::SecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L141{getPusSecondaryHeaderFactory}]]]
+getSecondaryHeader() const : std::shared_ptr<const SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L199{getSecondaryHeader}]]]
+getSecondaryHeader() : std::shared_ptr<SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L197{getSecondaryHeader}]]]
+getSecondaryHeaderAutoUpdateStatus() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L189{getSecondaryHeaderAutoUpdateStatus}]]]
+getSecondaryHeaderBytes() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L173{getSecondaryHeaderBytes}]]]
+getSecondaryHeaderBytes() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L175{getSecondaryHeaderBytes}]]]
+getSecondaryHeaderFactory() : SecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L134{getSecondaryHeaderFactory}]]]
+getSecondaryHeaderFactory() const : const SecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L136{getSecondaryHeaderFactory}]]]
+getSecondaryHeaderFlag() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L194{getSecondaryHeaderFlag}]]]
+serialize() : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L181{serialize}]]]
+setApplicationData(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L79{setApplicationData}]]]
+setApplicationData(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L71{setApplicationData}]]]
+setDataPacketSize(const std::u...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L150{setDataPacketSize}]]]
+setMissionProfile(const Missio...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L63{setMissionProfile}]]]
+setSecondaryHeader(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L98{setSecondaryHeader}]]]
+setSecondaryHeader(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L123{setSecondaryHeader}]]]
+setSecondaryHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L108{setSecondaryHeader}]]]
+setSecondaryHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L116{setSecondaryHeader}]]]
+setSecondaryHeader(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L88{setSecondaryHeader}]]]
+setSecondaryHeader(std::shared_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L131{setSecondaryHeader}]]]
+setSecondaryHeaderAutoUpdateStatus(const bool e...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L156{setSecondaryHeaderAutoUpdateStatus}]]]
+update() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L205{update}]]]
__
}
class "CRC16Config" as C_0016864569940544437548
class C_0016864569940544437548 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L41{CRC16Config}]] {
__
+finalXorValue : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L44{finalXorValue}]]]
+initialValue : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L43{initialValue}]]]
+polynomial : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L42{polynomial}]]]
}
class "Result<std::size_t>" as C_0012173917358234868545
class C_0012173917358234868545 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L296{Result}]] {
__
}
class "Packet" as C_0013265662939920414927
class C_0013265662939920414927 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L91{Packet}]] {
+Packet() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L94{Packet}]]]
..
+RegisterSecondaryHeader<T>() : ResultBool
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L260{deserialize}]]]
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L269{deserialize}]]]
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L279{deserialize}]]]
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L288{deserialize}]]]
+deserializeBounded(const std::v...) : ccsds::Result<std::size_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L315{deserializeBounded}]]]
+deserializeBounded(const std::v...) : ccsds::Result<std::size_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L305{deserializeBounded}]]]
+deserializeBounded(const std::v...) : ccsds::Result<std::size_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L296{deserializeBounded}]]]
+getApplicationDataBytes() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L366{getApplicationDataBytes}]]]
+getApplicationDataBytes() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L364{getApplicationDataBytes}]]]
+getCRC() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L385{getCRC}]]]
+getCRC() : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L383{getCRC}]]]
+getCRCVectorBytes() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L380{getCRCVectorBytes}]]]
+getCRCVectorBytes() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L378{getCRCVectorBytes}]]]
+getDataField() : DataField & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L399{getDataField}]]]
+getDataField() const : const DataField & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L401{getDataField}]]]
+getDataFieldMaximumSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L388{getDataFieldMaximumSize}]]]
+getFullDataFieldBytes() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L375{getFullDataFieldBytes}]]]
+getFullDataFieldBytes() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L373{getFullDataFieldBytes}]]]
+getFullPacketLength() : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L328{getFullPacketLength}]]]
+getFullPacketLength() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L330{getFullPacketLength}]]]
+getMissionProfile() const : const MissionProfile & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L137{getMissionProfile}]]]
+getPacketErrorControlMode() const : PacketErrorControlMode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L243{getPacketErrorControlMode}]]]
+getPacketErrorControlSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L250{getPacketErrorControlSize}]]]
+getPrimaryHeader() const : const Header & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L409{getPrimaryHeader}]]]
+getPrimaryHeader() : Header & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L407{getPrimaryHeader}]]]
+getPrimaryHeader64bit() : std::uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L319{getPrimaryHeader64bit}]]]
+getPrimaryHeader64bit() const : std::uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L321{getPrimaryHeader64bit}]]]
+getPrimaryHeaderBytes() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L349{getPrimaryHeaderBytes}]]]
+getPrimaryHeaderBytes() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L351{getPrimaryHeaderBytes}]]]
+getSecondaryHeader() : std::shared_ptr<SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L354{getSecondaryHeader}]]]
+getSecondaryHeader() const : std::shared_ptr<const SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L356{getSecondaryHeader}]]]
+getSecondaryHeaderBytes() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L359{getSecondaryHeaderBytes}]]]
+getSecondaryHeaderBytes() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L361{getSecondaryHeaderBytes}]]]
+getSecondaryHeaderFlag() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L393{getSecondaryHeaderFlag}]]]
+getSecondaryHeaderFlag() : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L391{getSecondaryHeaderFlag}]]]
+getSerializedSize() const : std::size_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L337{getSerializedSize}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L457{loadFromConfig}]]]
+loadFromConfigFile(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L449{loadFromConfigFile}]]]
+serialize() : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L346{serialize}]]]
+setApplicationData(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L194{setApplicationData}]]]
+setApplicationData(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L202{setApplicationData}]]]
+setCrcConfig(const std::u...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L426{setCrcConfig}]]]
+setCrcConfig(const CRC16C...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L415{setCrcConfig}]]]
+setDataFieldSize(std::uint16_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L225{setDataFieldSize}]]]
+setMissionProfile(const Missio...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L136{setMissionProfile}]]]
+setPacketErrorControlMode(PacketErrorC...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L240{setPacketErrorControlMode}]]]
+setPrimaryHeader(const Header...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L126{setPrimaryHeader}]]]
+setPrimaryHeader(std::uint64_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L111{setPrimaryHeader}]]]
+setPrimaryHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L119{setPrimaryHeader}]]]
+setPrimaryHeader(PrimaryHeade...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L103{setPrimaryHeader}]]]
+setSecondaryHeader(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L186{setSecondaryHeader}]]]
+setSecondaryHeader(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L133{setSecondaryHeader}]]]
+setSecondaryHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L159{setSecondaryHeader}]]]
+setSecondaryHeader(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L169{setSecondaryHeader}]]]
+setSecondaryHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L178{setSecondaryHeader}]]]
+setSequenceCount(std::uint16_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L218{setSequenceCount}]]]
+setSequenceFlags(ESequenceFla...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L209{setSequenceFlags}]]]
+setUpdatePacketEnable(bool enable) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L232{setUpdatePacketEnable}]]]
+update() : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L441{update}]]]
__
}
class "Validator" as C_0018031729085130461143
class C_0018031729085130461143 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L28{Validator}]] {
+Validator() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L31{Validator}]]]
+Validator(const Packet...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L41{Validator}]]]
+~Validator() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L34{~Validator}]]]
..
+clear() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L88{clear}]]]
+configure(bool validat...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L58{configure}]]]
+getReport() const : std::vector<bool> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L81{getReport}]]]
+setTemplatePacket(const Packet...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L47{setTemplatePacket}]]]
+validate(const Packet...) : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L68{validate}]]]
__
}
class "Manager" as C_0000941024306421117083
class C_0000941024306421117083 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L47{Manager}]] {
+Manager() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L50{Manager}]]]
+Manager(Packet packet) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L60{Manager}]]]
..
+addPacket(Packet packet) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L226{addPacket}]]]
+addPacketFromBuffer(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L234{addPacketFromBuffer}]]]
+clear() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L275{clear}]]]
+clearPackets() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L281{clearPackets}]]]
+getApplicationDataBuffer() : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L193{getApplicationDataBuffer}]]]
+getApplicationDataBufferAtIndex(std::uint16_...) : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L200{getApplicationDataBufferAtIndex}]]]
+getAutoSequenceCountEnable() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L152{getAutoSequenceCountEnable}]]]
+getAutoUpdateEnable() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L206{getAutoUpdateEnable}]]]
+getDataFieldSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L118{getDataFieldSize}]]]
+getPacketBufferAtIndex(std::uint16_...) : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L180{getPacketBufferAtIndex}]]]
+getPacketTemplate() : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L173{getPacketTemplate}]]]
+getPackets() const : std::vector<Packet> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L216{getPackets}]]]
+getPackets() : std::vector<Packet> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L214{getPackets}]]]
+getPacketsBuffer() const : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L187{getPacketsBuffer}]]]
+getPacketsReference() : std::vector<Packet> & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L295{getPacketsReference}]]]
+getSequenceCount() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L164{getSequenceCount}]]]
+getSyncPattern() const : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L77{getSyncPattern}]]]
+getSyncPatternEnable() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L86{getSyncPatternEnable}]]]
+getTemplate() : Packet [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L209{getTemplate}]]]
+getTemplate() const : Packet [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L211{getTemplate}]]]
+getTotalPackets() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L203{getTotalPackets}]]]
+getValidatorReference() : Validator & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L288{getValidatorReference}]]]
+load(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L241{load}]]]
+load(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L248{load}]]]
+loadTemplateConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L108{loadTemplateConfig}]]]
+loadTemplateConfigFile(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L101{loadTemplateConfigFile}]]]
+read(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L255{read}]]]
+readTemplate(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L269{readTemplate}]]]
+setApplicationData(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L128{setApplicationData}]]]
+setAutoSequenceCountEnable(bool enable) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L149{setAutoSequenceCountEnable}]]]
+setAutoUpdateEnable(bool enable) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L134{setAutoUpdateEnable}]]]
+setAutoValidateEnable(bool enable) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L140{setAutoValidateEnable}]]]
+setDataFieldSize(std::uint16_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L115{setDataFieldSize}]]]
+setPacketTemplate(Packet packet) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L94{setPacketTemplate}]]]
+setSequenceCount(std::uint16_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L161{setSequenceCount}]]]
+setSyncPattern(std::uint32_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L74{setSyncPattern}]]]
+setSyncPatternEnable(bool enable) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L83{setSyncPatternEnable}]]]
+write(const std::s...) const : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L262{write}]]]
__
}
}
class "ParsedPacket" as C_0005436190735706831690
class C_0005436190735706831690 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/src/CCSDSPacket.cpp#L16{ParsedPacket}]] {
__
+dataField : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/src/CCSDSPacket.cpp#L18{dataField}]]]
+header : ccsds::Header [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/src/CCSDSPacket.cpp#L17{header}]]]
+receivedCRC : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/src/CCSDSPacket.cpp#L19{receivedCRC}]]]
}
C_0017566881135794494958 o-- C_0009051388942408461891 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L67{m_code}]] : -m_code
C_0008099319371458986879 o-- C_0017566881135794494958 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L92{data}]] : -data
C_0008186123745702387052 ..|> C_0008099319371458986879
C_0011294920384177675248 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L153{}]]
C_0011294920384177675248 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L153{}]]
C_0011294920384177675248 ..> C_0011505254011848722045 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L217{}]]
C_0011294920384177675248 o-- C_0006565293471114675048 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L231{m_status}]] : -m_status
C_0016810538617857061367 ..|> C_0008099319371458986879
C_0018286355310635740643 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L43{}]]
C_0018286355310635740643 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L43{}]]
C_0018286355310635740643 ..> C_0016810538617857061367 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L86{}]]
C_0005445694194400424073 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L64{}]]
C_0005445694194400424073 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L64{}]]
C_0005445694194400424073 ..> C_0003434639916644007055 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L71{}]]
C_0005445694194400424073 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L95{}]]
C_0005445694194400424073 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L105{}]]
C_0014736019873459950331 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L145{}]]
C_0014736019873459950331 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L145{}]]
C_0014736019873459950331 ..> C_0003434639916644007055 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L165{}]]
C_0014736019873459950331 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L171{}]]
C_0005445694194400424073 <|-- C_0014736019873459950331
C_0009041847757797157790 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L34{}]]
C_0009041847757797157790 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L34{}]]
C_0009041847757797157790 ..> C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L47{}]]
C_0009041847757797157790 ..> C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L57{m_creators}]] : -m_creators
C_0010465517018640617180 o-- C_0011169860713497893350 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L39{epoch}]] : +epoch
C_0010465517018640617180 o-- C_0003117097434587954110 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L40{pField}]] : +pField
C_0017820635191381806822 ..> C_0006294303417563364908 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L23{}]]
C_0017820635191381806822 ..> C_0001829865898408684403 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L25{}]]
C_0017820635191381806822 ..> C_0003434639916644007055 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L43{}]]
C_0017820635191381806822 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L47{}]]
C_0017820635191381806822 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L47{}]]
C_0017820635191381806822 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L47{}]]
C_0017820635191381806822 o-- C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L62{m_profile}]] : #m_profile
C_0005445694194400424073 <|-- C_0017820635191381806822
C_0004810502936549036890 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L78{}]]
C_0004810502936549036890 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L78{}]]
C_0004810502936549036890 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L88{}]]
C_0004810502936549036890 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L92{}]]
C_0017820635191381806822 <|-- C_0004810502936549036890
C_0004398363156631507099 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L122{}]]
C_0004398363156631507099 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L122{}]]
C_0004398363156631507099 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L128{}]]
C_0004398363156631507099 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L132{}]]
C_0004398363156631507099 o-- C_0014692306963991656514 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L142{m_timestamp}]] : #m_timestamp
C_0017820635191381806822 <|-- C_0004398363156631507099
C_0001755478337597829079 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L150{}]]
C_0001755478337597829079 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L155{}]]
C_0001755478337597829079 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L155{}]]
C_0004810502936549036890 <|-- C_0001755478337597829079
C_0017247575000911418816 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L188{}]]
C_0017247575000911418816 ..> C_0014692306963991656514 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L192{}]]
C_0017247575000911418816 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L198{}]]
C_0017247575000911418816 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L198{}]]
C_0017247575000911418816 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L206{}]]
C_0004398363156631507099 <|-- C_0017247575000911418816
C_0004296692240053397319 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L169{}]]
C_0004296692240053397319 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L174{}]]
C_0004296692240053397319 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L174{}]]
C_0004810502936549036890 <|-- C_0004296692240053397319
C_0009041677057813291073 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L219{}]]
C_0009041677057813291073 ..> C_0014692306963991656514 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L225{}]]
C_0009041677057813291073 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L233{}]]
C_0009041677057813291073 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L233{}]]
C_0009041677057813291073 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L243{}]]
C_0004398363156631507099 <|-- C_0009041677057813291073
C_0002158309051506416943 ..> C_0006294303417563364908 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L18{}]]
C_0002158309051506416943 ..> C_0001829865898408684403 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L18{}]]
C_0002158309051506416943 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L18{}]]
C_0002158309051506416943 ..> C_0007514998099265917869 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{}]]
C_0002158309051506416943 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{}]]
C_0002158309051506416943 ..> C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{}]]
C_0013482125278780870275 o-- C_0006294303417563364908 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L49{pusRevision}]] : +pusRevision
C_0013482125278780870275 o-- C_0001829865898408684403 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L50{direction}]] : +direction
C_0013482125278780870275 o-- C_0011113483064328568240 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L53{packetErrorControl}]] : +packetErrorControl
C_0013482125278780870275 o-- C_0014027148995399468784 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L55{telemetryTimeCode}]] : +telemetryTimeCode
C_0013482125278780870275 o-- C_0010465517018640617180 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L56{telemetryCuc}]] : +telemetryCuc
C_0007514998099265917869 ..|> C_0008099319371458986879
C_0003434639916644007055 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L63{}]]
C_0003434639916644007055 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L63{}]]
C_0003434639916644007055 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L123{}]]
C_0003434639916644007055 ..> C_0016810538617857061367 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L181{}]]
C_0003434639916644007055 --> C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L211{m_secondaryHeader}]] : -m_secondaryHeader
C_0003434639916644007055 o-- C_0009041847757797157790 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L212{m_secondaryHeaderFactory}]] : -m_secondaryHeaderFactory
C_0003434639916644007055 o-- C_0002158309051506416943 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L213{m_pusSecondaryHeaderFactory}]] : -m_pusSecondaryHeaderFactory
C_0003434639916644007055 o-- C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L214{m_missionProfile}]] : -m_missionProfile
C_0003434639916644007055 <.. C_0013265662939920414927 : +<<friend>>
C_0012173917358234868545 ..|> C_0008099319371458986879
C_0013265662939920414927 ..> C_0011505254011848722045 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L103{}]]
C_0013265662939920414927 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L103{}]]
C_0013265662939920414927 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L103{}]]
C_0013265662939920414927 ..> C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L134{}]]
C_0013265662939920414927 ..> C_0002282814802499769197 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L209{}]]
C_0013265662939920414927 ..> C_0011113483064328568240 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L240{}]]
C_0013265662939920414927 ..> C_0012173917358234868545 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L296{}]]
C_0013265662939920414927 ..> C_0016810538617857061367 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L346{}]]
C_0013265662939920414927 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L457{}]]
C_0013265662939920414927 o-- C_0011294920384177675248 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L464{m_primaryHeader}]] : -m_primaryHeader
C_0013265662939920414927 o-- C_0003434639916644007055 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L465{m_dataField}]] : -m_dataField
C_0013265662939920414927 o-- C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L466{m_missionProfile}]] : -m_missionProfile
C_0013265662939920414927 o-- C_0016864569940544437548 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L468{m_CRC16Config}]] : -m_CRC16Config
C_0018031729085130461143 ..> C_0011294920384177675248 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L104{}]]
C_0018031729085130461143 o-- C_0013265662939920414927 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L106{m_templatePacket}]] : -m_templatePacket
C_0018031729085130461143 o-- C_0016864569940544437548 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L113{m_CRCConfig}]] : -m_CRCConfig
C_0000941024306421117083 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L94{}]]
C_0000941024306421117083 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L94{}]]
C_0000941024306421117083 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L108{}]]
C_0000941024306421117083 ..> C_0016810538617857061367 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L173{}]]
C_0000941024306421117083 ..> C_0011113483064328568240 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L305{}]]
C_0000941024306421117083 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L306{}]]
C_0000941024306421117083 o-- C_0013265662939920414927 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L310{m_templatePacket}]] : -m_templatePacket
C_0000941024306421117083 o-- C_0013265662939920414927 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L315{m_packets}]] : -m_packets
C_0000941024306421117083 o-- C_0018031729085130461143 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L318{m_validator}]] : -m_validator
C_0005436190735706831690 o-- C_0011294920384177675248 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/src/CCSDSPacket.cpp#L17{header}]] : +header

'Generated with clang-uml, version 0.6.3-59-gdfa2271
'LLVM version Ubuntu clang version 17.0.6 (9ubuntu1)
@enduml
