@startuml
title CCSDS::Manager UML Diagram
package [CCSDS] as C_0007081182557856067311 {
enum "ErrorCode" as C_0009397388538647267500
enum C_0009397388538647267500 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L15{ErrorCode}]] {
NONE
UNKNOWN_ERROR
NO_DATA
INVALID_DATA
INVALID_HEADER_DATA
INVALID_SECONDARY_HEADER_DATA
INVALID_APPLICATION_DATA
NULL_POINTER
INVALID_CHECKSUM
VALIDATION_FAILURE
TEMPLATE_SET_FAILURE
FILE_READ_ERROR
FILE_WRITE_ERROR
CONFIG_FILE_ERROR
}
class "Error" as C_0016667887324179082906
class C_0016667887324179082906 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L39{Error}]] {
+Error(const ErrorC...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L46{Error}]]]
..
+code() const : ErrorCode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L54{code}]]]
+message() const : const std::string & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L60{message}]]]
__
}
class "Result<T>" as C_0008471204632575367201
class C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L77{Result}]] {
+Result(T value) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L85{Result}]]]
+Result(Error error) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L92{Result}]]]
..
+error() const : Error [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L115{error}]]]
+has_value() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L99{has_value}]]]
+operator bool() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L123{operator bool}]]]
+value() : T & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L108{value}]]]
+value() const : const T & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L109{value}]]]
__
}
enum "ESequenceFlag" as C_0009395536347375124815
enum C_0009395536347375124815 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L19{ESequenceFlag}]] {
CONTINUING_SEGMENT
FIRST_SEGMENT
LAST_SEGMENT
UNSEGMENTED
}
class "PrimaryHeader" as C_0011016081288581091098
class C_0011016081288581091098 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L41{PrimaryHeader}]] {
+PrimaryHeader(const uint8_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L66{PrimaryHeader}]]]
__
+APID : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L46{APID}]]]
+dataFieldHeaderFlag : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L45{dataFieldHeaderFlag}]]]
+dataLength : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L53{dataLength}]]]
+sequenceCount : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L50{sequenceCount}]]]
+sequenceFlags : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L49{sequenceFlags}]]]
+type : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L44{type}]]]
+versionNumber : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L43{versionNumber}]]]
}
class "Result<bool>" as C_0008762487699986143535
class C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L135{Result}]] {
__
}
class "Header" as C_0000066884519575390086
class C_0000066884519575390086 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L80{Header}]] {
+Header() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L82{Header}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L148{deserialize}]]]
+getAPID() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L87{getAPID}]]]
+getDataFieldHeaderFlag() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L86{getDataFieldHeaderFlag}]]]
+getDataLength() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L90{getDataLength}]]]
+getFullHeader() : uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L108{getFullHeader}]]]
+getSequenceCount() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L89{getSequenceCount}]]]
+getSequenceFlags() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L88{getSequenceFlags}]]]
+getType() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L85{getType}]]]
+getVersionNumber() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L84{getVersionNumber}]]]
+serialize() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L98{serialize}]]]
+setAPID(const uint16...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L119{setAPID}]]]
+setData(const Primar...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L160{setData}]]]
+setData(const uint64...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L135{setData}]]]
+setDataFieldHeaderFlag(const uint8_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L118{setDataFieldHeaderFlag}]]]
+setDataLength(const uint16...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L122{setDataLength}]]]
+setSequenceCount(const uint16...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L121{setSequenceCount}]]]
+setSequenceFlags(const uint8_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L120{setSequenceFlags}]]]
+setType(const uint8_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L117{setType}]]]
+setVersionNumber(const uint8_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L116{setVersionNumber}]]]
__
}
class "Result<std::vector<uint8_t>>" as C_0003681749600908501807
class C_0003681749600908501807 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L38{Result}]] {
__
}
abstract "SecondaryHeaderAbstract" as C_0015357895956836170771
abstract C_0015357895956836170771 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L16{SecondaryHeaderAbstract}]] {
+~SecondaryHeaderAbstract() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L18{~SecondaryHeaderAbstract}]]]
..
{abstract} +deserialize(const std::v...) = 0 : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L24{deserialize}]]]
{abstract} +getSize() const = 0 : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L40{getSize}]]]
{abstract} +getType() const = 0 : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L52{getType}]]]
{abstract} +loadFromConfig(const Config...) = 0 : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L55{loadFromConfig}]]]
{abstract} +serialize() const = 0 : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L46{serialize}]]]
+setVariableLength(const bool b...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L56{setVariableLength}]]]
{abstract} +update(DataField * ...) = 0 : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L34{update}]]]
__
+variableLength : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L57{variableLength}]]]
}
class "BufferHeader" as C_0002331772882390791170
class C_0002331772882390791170 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L74{BufferHeader}]] {
+BufferHeader() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L76{BufferHeader}]]]
+BufferHeader(const std::v...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L81{BufferHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L84{deserialize}]]]
+getSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L86{getSize}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L87{getType}]]]
+loadFromConfig(const Config...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L91{loadFromConfig}]]]
+serialize() const : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L89{serialize}]]]
+update(DataField * ...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L90{update}]]]
__
}
class "SecondaryHeaderFactory" as C_0000143976543200677522
class C_0000143976543200677522 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L18{SecondaryHeaderFactory}]] {
+SecondaryHeaderFactory() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L23{SecondaryHeaderFactory}]]]
..
+create(const std::s...) : std::shared_ptr<SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L50{create}]]]
+registerType(std::shared_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L38{registerType}]]]
+typeIsRegistered(const std::s...) : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L65{typeIsRegistered}]]]
__
}
class "DataField" as C_0006701855109527716313
class C_0006701855109527716313 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L25{DataField}]] {
+DataField() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L27{DataField}]]]
+~DataField() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L34{~DataField}]]]
..
+RegisterSecondaryHeader<T>() : void
+getApplicationData() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L253{getApplicationData}]]]
+getApplicationDataBytesSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L206{getApplicationDataBytesSize}]]]
+getDataFieldAbsoluteBytesSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L199{getDataFieldAbsoluteBytesSize}]]]
+getDataFieldAvailableBytesSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L224{getDataFieldAvailableBytesSize}]]]
+getDataFieldHeader() : SecondaryHeaderAbstract & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L172{getDataFieldHeader}]]]
+getDataFieldHeaderAutoUpdateStatus() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L256{getDataFieldHeaderAutoUpdateStatus}]]]
+getDataFieldHeaderBytes() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L234{getDataFieldHeaderBytes}]]]
+getDataFieldHeaderFactory() : SecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L164{getDataFieldHeaderFactory}]]]
+getDataFieldHeaderFlag() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L263{getDataFieldHeaderFlag}]]]
+getDataFieldUsedBytesSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L215{getDataFieldUsedBytesSize}]]]
+getSecondaryHeader() : std::shared_ptr<SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L272{getSecondaryHeader}]]]
+serialize() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L244{serialize}]]]
+setApplicationData(const uint8_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L73{setApplicationData}]]]
+setApplicationData(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L59{setApplicationData}]]]
+setDataFieldHeader(const uint8_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L105{setDataFieldHeader}]]]
+setDataFieldHeader(const uint8_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L88{setDataFieldHeader}]]]
+setDataFieldHeader(std::shared_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L157{setDataFieldHeader}]]]
+setDataFieldHeader(const Config...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L149{setDataFieldHeader}]]]
+setDataFieldHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L138{setDataFieldHeader}]]]
+setDataFieldHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L122{setDataFieldHeader}]]]
+setDataFieldHeaderAutoUpdateStatus(const bool e...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L189{setDataFieldHeaderAutoUpdateStatus}]]]
+setDataPacketSize(const uint16...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L183{setDataPacketSize}]]]
+update() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L282{update}]]]
__
}
class "CRC16Config" as C_0003994627686254228849
class C_0003994627686254228849 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L35{CRC16Config}]] {
__
+finalXorValue : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L38{finalXorValue}]]]
+initialValue : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L37{initialValue}]]]
+polynomial : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L36{polynomial}]]]
}
class "Packet" as C_0001106029959005870872
class C_0001106029959005870872 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L59{Packet}]] {
+Packet() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L61{Packet}]]]
..
+RegisterSecondaryHeader<T>() : void
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L257{deserialize}]]]
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L254{deserialize}]]]
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L251{deserialize}]]]
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L248{deserialize}]]]
+getApplicationDataBytes() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L312{getApplicationDataBytes}]]]
+getCRC() : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L340{getCRC}]]]
+getCRCVectorBytes() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L329{getCRCVectorBytes}]]]
+getDataField() : DataField & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L349{getDataField}]]]
+getDataFieldHeaderBytes() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L305{getDataFieldHeaderBytes}]]]
+getDataFieldHeaderFlag() : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L346{getDataFieldHeaderFlag}]]]
+getDataFieldMaximumSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L343{getDataFieldMaximumSize}]]]
+getFullDataFieldBytes() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L319{getFullDataFieldBytes}]]]
+getFullPacketLength() : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L274{getFullPacketLength}]]]
+getPrimaryHeader() : Header & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L352{getPrimaryHeader}]]]
+getPrimaryHeader64bit() : uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L268{getPrimaryHeader64bit}]]]
+getPrimaryHeaderBytes() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L298{getPrimaryHeaderBytes}]]]
+loadFromConfig(const Config...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L406{loadFromConfig}]]]
+loadFromConfigFile(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L398{loadFromConfigFile}]]]
+serialize() : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L287{serialize}]]]
+setApplicationData(const uint8_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L214{setApplicationData}]]]
+setApplicationData(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L200{setApplicationData}]]]
+setCrcConfig(const uint16...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L381{setCrcConfig}]]]
+setCrcConfig(const CRC16C...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L365{setCrcConfig}]]]
+setDataFieldHeader(const uint8_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L187{setDataFieldHeader}]]]
+setDataFieldHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L173{setDataFieldHeader}]]]
+setDataFieldHeader(const uint8_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L160{setDataFieldHeader}]]]
+setDataFieldHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L144{setDataFieldHeader}]]]
+setDataFieldHeader(const std::s...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L117{setDataFieldHeader}]]]
+setDataFieldSize(uint16_t size) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L239{setDataFieldSize}]]]
+setPrimaryHeader(const Header...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L106{setPrimaryHeader}]]]
+setPrimaryHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L96{setPrimaryHeader}]]]
+setPrimaryHeader(PrimaryHeade...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L72{setPrimaryHeader}]]]
+setPrimaryHeader(uint64_t data) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L84{setPrimaryHeader}]]]
+setSequenceCount(uint16_t count) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L228{setSequenceCount}]]]
+setSequenceFlags(ESequenceFla...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L225{setSequenceFlags}]]]
+setUpdatePacketEnable(bool enable) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L245{setUpdatePacketEnable}]]]
+update() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L390{update}]]]
__
}
class "Validator" as C_0015262608491158149275
class C_0015262608491158149275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L14{Validator}]] {
+Validator() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L17{Validator}]]]
+Validator(const Packet...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L26{Validator}]]]
+~Validator() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L20{~Validator}]]]
..
+clear() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L70{clear}]]]
+configure(bool validat...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L41{configure}]]]
+getReport() const : std::vector<bool> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L64{getReport}]]]
+setTemplatePacket(const Packet...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L33{setTemplatePacket}]]]
+validate(const Packet...) : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L48{validate}]]]
__
}
class "Manager" as C_0014627802343853026005
class C_0014627802343853026005 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L18{Manager}]] {
+Manager() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L23{Manager}]]]
+Manager(Packet packet) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L30{Manager}]]]
..
+addPacket(Packet packet) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L195{addPacket}]]]
+addPacketFromBuffer(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L202{addPacketFromBuffer}]]]
+clear() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L242{clear}]]]
+clearPackets() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L247{clearPackets}]]]
+getApplicationDataBuffer() : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L152{getApplicationDataBuffer}]]]
+getApplicationDataBufferAtIndex(uint16_t index) : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L160{getApplicationDataBufferAtIndex}]]]
+getAutoUpdateEnable() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L174{getAutoUpdateEnable}]]]
+getDataFieldSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L100{getDataFieldSize}]]]
+getPacketBufferAtIndex(uint16_t index) : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L137{getPacketBufferAtIndex}]]]
+getPacketTemplate() : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L129{getPacketTemplate}]]]
+getPackets() : std::vector<Packet> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L188{getPackets}]]]
+getPacketsBuffer() const : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L145{getPacketsBuffer}]]]
+getPacketsReference() : std::vector<Packet> & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L261{getPacketsReference}]]]
+getSyncPattern() const : uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L51{getSyncPattern}]]]
+getSyncPatternEnable() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L65{getSyncPatternEnable}]]]
+getTemplate() : Packet [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L181{getTemplate}]]]
+getTotalPackets() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L167{getTotalPackets}]]]
+getValidatorReference() : Validator & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L254{getValidatorReference}]]]
+load(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L209{load}]]]
+load(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L216{load}]]]
+loadTemplateConfig(const Config...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L86{loadTemplateConfig}]]]
+loadTemplateConfigFile(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L79{loadTemplateConfigFile}]]]
+read(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L223{read}]]]
+readTemplate(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L237{readTemplate}]]]
+setApplicationData(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L108{setApplicationData}]]]
+setAutoUpdateEnable(bool enable) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L115{setAutoUpdateEnable}]]]
+setAutoValidateEnable(bool enable) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L122{setAutoValidateEnable}]]]
+setDataFieldSize(uint16_t size) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L93{setDataFieldSize}]]]
+setPacketTemplate(Packet packet) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L72{setPacketTemplate}]]]
+setSyncPattern(uint32_t syn...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L44{setSyncPattern}]]]
+setSyncPatternEnable(bool enable) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L58{setSyncPatternEnable}]]]
+write(const std::s...) const : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L230{write}]]]
__
}
}
class "Config" as C_0008289891971916880997
class C_0008289891971916880997 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L10{Config}]] {
+get<T>(const std::s...) const : CCSDS::Result<T>
+isKey(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L29{isKey}]]]
+load(const std::s...) : CCSDS::ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L15{load}]]]
__
}
class "PusA" as C_0001404029779718103303
class C_0001404029779718103303 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L21{PusA}]] {
+PusA() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L23{PusA}]]]
+PusA(const uint8_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L33{PusA}]]]
..
+deserialize(const std::v...) : CCSDS::ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L49{deserialize}]]]
+getDataLength() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L44{getDataLength}]]]
+getServiceSubtype() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L42{getServiceSubtype}]]]
+getServiceType() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L41{getServiceType}]]]
+getSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L45{getSize}]]]
+getSourceID() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L43{getSourceID}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L46{getType}]]]
+getVersion() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L40{getVersion}]]]
+loadFromConfig(const ::Conf...) : CCSDS::ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L51{loadFromConfig}]]]
+serialize() const : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L48{serialize}]]]
+update(CCSDS::DataF...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L50{update}]]]
__
}
class "PusB" as C_0014410093318812969362
class C_0014410093318812969362 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L77{PusB}]] {
+PusB() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L79{PusB}]]]
+PusB(const uint8_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L90{PusB}]]]
..
+deserialize(const std::v...) : CCSDS::ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L106{deserialize}]]]
+getDataLength() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L101{getDataLength}]]]
+getEventID() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L100{getEventID}]]]
+getServiceSubtype() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L98{getServiceSubtype}]]]
+getServiceType() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L97{getServiceType}]]]
+getSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L102{getSize}]]]
+getSourceID() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L99{getSourceID}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L103{getType}]]]
+getVersion() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L96{getVersion}]]]
+loadFromConfig(const ::Conf...) : CCSDS::ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L108{loadFromConfig}]]]
+serialize() const : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L105{serialize}]]]
+update(CCSDS::DataF...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L107{update}]]]
__
}
class "PusC" as C_0004565611741543840631
class C_0004565611741543840631 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L135{PusC}]] {
+PusC() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L137{PusC}]]]
+PusC(const uint8_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L148{PusC}]]]
..
+deserialize(const std::v...) : CCSDS::ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L166{deserialize}]]]
+getDataLength() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L161{getDataLength}]]]
+getServiceSubtype() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L158{getServiceSubtype}]]]
+getServiceType() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L157{getServiceType}]]]
+getSize() const : uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L162{getSize}]]]
+getSourceID() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L159{getSourceID}]]]
+getTimeCode() const : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L160{getTimeCode}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L163{getType}]]]
+getVersion() const : uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L156{getVersion}]]]
+loadFromConfig(const ::Conf...) : CCSDS::ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L168{loadFromConfig}]]]
+serialize() const : std::vector<uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L165{serialize}]]]
+update(CCSDS::DataF...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L167{update}]]]
__
}
C_0016667887324179082906 o-- C_0009397388538647267500 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L63{m_code}]] : -m_code
C_0008471204632575367201 o-- C_0016667887324179082906 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L78{data}]] : -data
C_0008762487699986143535 ..|> C_0008471204632575367201
C_0000066884519575390086 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L135{}]]
C_0000066884519575390086 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L135{}]]
C_0000066884519575390086 ..> C_0011016081288581091098 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSHeader.h#L160{}]]
C_0003681749600908501807 ..|> C_0008471204632575367201
C_0015357895956836170771 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L24{}]]
C_0015357895956836170771 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L24{}]]
C_0015357895956836170771 ..> C_0006701855109527716313 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L34{}]]
C_0015357895956836170771 ..> C_0008289891971916880997 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L55{}]]
C_0002331772882390791170 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L84{}]]
C_0002331772882390791170 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L84{}]]
C_0002331772882390791170 ..> C_0006701855109527716313 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L90{}]]
C_0002331772882390791170 ..> C_0008289891971916880997 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L91{}]]
C_0015357895956836170771 <|-- C_0002331772882390791170
C_0000143976543200677522 o-- C_0015357895956836170771 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L78{m_creators}]] : -m_creators
C_0006701855109527716313 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L59{}]]
C_0006701855109527716313 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L59{}]]
C_0006701855109527716313 ..> C_0008289891971916880997 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L149{}]]
C_0006701855109527716313 --> C_0015357895956836170771 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L285{m_secondaryHeader}]] : -m_secondaryHeader
C_0006701855109527716313 o-- C_0000143976543200677522 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L286{m_secondaryHeaderFactory}]] : -m_secondaryHeaderFactory
C_0001106029959005870872 ..> C_0011016081288581091098 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L72{}]]
C_0001106029959005870872 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L84{}]]
C_0001106029959005870872 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L84{}]]
C_0001106029959005870872 ..> C_0015357895956836170771 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L117{}]]
C_0001106029959005870872 ..> C_0009395536347375124815 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L225{}]]
C_0001106029959005870872 ..> C_0008289891971916880997 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L406{}]]
C_0001106029959005870872 o-- C_0000066884519575390086 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L410{m_primaryHeader}]] : -m_primaryHeader
C_0001106029959005870872 o-- C_0006701855109527716313 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L411{m_dataField}]] : -m_dataField
C_0001106029959005870872 o-- C_0003994627686254228849 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSPacket.h#L413{m_CRC16Config}]] : -m_CRC16Config
C_0015262608491158149275 o-- C_0001106029959005870872 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L73{m_templatePacket}]] : -m_templatePacket
C_0015262608491158149275 o-- C_0003994627686254228849 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSValidator.h#L80{m_CRCConfig}]] : -m_CRCConfig
C_0014627802343853026005 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L72{}]]
C_0014627802343853026005 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L72{}]]
C_0014627802343853026005 ..> C_0008289891971916880997 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L86{}]]
C_0014627802343853026005 ..> C_0003681749600908501807 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L129{}]]
C_0014627802343853026005 o-- C_0001106029959005870872 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L264{m_templatePacket}]] : -m_templatePacket
C_0014627802343853026005 o-- C_0001106029959005870872 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L269{m_packets}]] : -m_packets
C_0014627802343853026005 o-- C_0015262608491158149275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSManager.h#L272{m_validator}]] : -m_validator
C_0008289891971916880997 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L15{}]]
C_0008289891971916880997 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L15{}]]
C_0008289891971916880997 ..> C_0003681749600908501807 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L38{}]]
C_0001404029779718103303 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L49{}]]
C_0001404029779718103303 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L49{}]]
C_0001404029779718103303 ..> C_0006701855109527716313 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L50{}]]
C_0001404029779718103303 ..> C_0008289891971916880997 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L51{}]]
C_0015357895956836170771 <|-- C_0001404029779718103303
C_0014410093318812969362 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L106{}]]
C_0014410093318812969362 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L106{}]]
C_0014410093318812969362 ..> C_0006701855109527716313 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L107{}]]
C_0014410093318812969362 ..> C_0008289891971916880997 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L108{}]]
C_0015357895956836170771 <|-- C_0014410093318812969362
C_0004565611741543840631 ..> C_0008762487699986143535 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L166{}]]
C_0004565611741543840631 ..> C_0008471204632575367201 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L166{}]]
C_0004565611741543840631 ..> C_0006701855109527716313 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L167{}]]
C_0004565611741543840631 ..> C_0008289891971916880997 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusServices.h#L168{}]]
C_0015357895956836170771 <|-- C_0004565611741543840631

'Generated with clang-uml, version 0.6.2-24-ge1152da
'LLVM version Ubuntu clang version 17.0.6 (9ubuntu1)
@enduml
