@startuml
title ccsds::DataField UML Diagram
package [ccsds] as C_0015722493921447645547 {
enum "ErrorCode" as C_0009051388942408461891
enum C_0009051388942408461891 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L29{ErrorCode}]] {
NONE
UNKNOWN_ERROR
NO_DATA
INVALID_DATA
INVALID_HEADER_DATA
INVALID_SECONDARY_HEADER_DATA
INVALID_APPLICATION_DATA
NULL_POINTER
INVALID_CHECKSUM
VALIDATION_FAILURE
TEMPLATE_SET_FAILURE
FILE_READ_ERROR
FILE_WRITE_ERROR
CONFIG_FILE_ERROR
}
class "Error" as C_0017566881135794494958
class C_0017566881135794494958 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L50{Error}]] {
+Error(const ErrorC...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L57{Error}]]]
..
+code() const : ErrorCode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L61{code}]]]
+message() const : const std::string & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L64{message}]]]
__
}
class "Result<T>" as C_0008099319371458986879
class C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L91{Result}]] {
+Result(T value) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L99{Result}]]]
+Result(Error error) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L105{Result}]]]
..
+error() const : Error [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L128{error}]]]
+has_value() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L108{has_value}]]]
+operator bool() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L131{operator bool}]]]
+value() : T & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L116{value}]]]
+value() const : const T & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L122{value}]]]
__
}
class "Result<bool>" as C_0008186123745702387052
class C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L43{Result}]] {
__
}
class "Result<std::vector<uint8_t>>" as C_0016810538617857061367
class C_0016810538617857061367 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L86{Result}]] {
__
}
class "Config" as C_0018286355310635740643
class C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L32{Config}]] {
+get<T>(const std::s...) const : Result<T>
+isKey(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L69{isKey}]]]
+load(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L43{load}]]]
__
}
abstract "SecondaryHeaderAbstract" as C_0005445694194400424073
abstract C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L53{SecondaryHeaderAbstract}]] {
+~SecondaryHeaderAbstract() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L56{~SecondaryHeaderAbstract}]]]
..
{abstract} +deserialize(const std::v...) = 0 : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L64{deserialize}]]]
{abstract} +getSize() const = 0 : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L77{getSize}]]]
{abstract} +getType() const = 0 : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L89{getType}]]]
+isPusHeader() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L92{isPusHeader}]]]
{abstract} +loadFromConfig(const ccsds:...) = 0 : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L105{loadFromConfig}]]]
+matchesMissionProfile(const Missio...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L95{matchesMissionProfile}]]]
{abstract} +serialize() const = 0 : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L83{serialize}]]]
+setVariableLength(const bool b...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L112{setVariableLength}]]]
{abstract} +update(DataField * ...) = 0 : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L71{update}]]]
__
+variableLength : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L118{variableLength}]]]
}
class "BufferHeader" as C_0014736019873459950331
class C_0014736019873459950331 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L129{BufferHeader}]] {
+BufferHeader() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L132{BufferHeader}]]]
+BufferHeader(const std::v...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L138{BufferHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L145{deserialize}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L151{getSize}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L156{getType}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L171{loadFromConfig}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L159{serialize}]]]
+update(DataField * ...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L165{update}]]]
__
}
class "SecondaryHeaderFactory" as C_0009041847757797157790
class C_0009041847757797157790 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L18{SecondaryHeaderFactory}]] {
+create(const std::s...) const : std::shared_ptr<SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L47{create}]]]
+registerCreator(const std::s...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L34{registerCreator}]]]
+registerType<T>() : ResultBool
+typeIsRegistered(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L52{typeIsRegistered}]]]
__
}
package [time] as C_0004898341130237538964 {
enum "Format" as C_0014027148995399468784
enum C_0014027148995399468784 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L19{Format}]] {
None
Cuc
}
enum "Epoch" as C_0011169860713497893350
enum C_0011169860713497893350 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L25{Epoch}]] {
Unspecified
Ccsds1958Tai
AgencyDefined
}
enum "PFieldMode" as C_0003117097434587954110
enum C_0003117097434587954110 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L32{PFieldMode}]] {
Implicit
Explicit
}
class "CucConfiguration" as C_0010465517018640617180
class C_0010465517018640617180 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L38{CucConfiguration}]] {
__
+coarseOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L41{coarseOctets}]]]
+epoch : Epoch [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L39{epoch}]]]
+fineOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L42{fineOctets}]]]
+pField : PFieldMode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L40{pField}]]]
}
class "CucTime" as C_0014692306963991656514
class C_0014692306963991656514 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L46{CucTime}]] {
+operator!=(const CucTim...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L53{operator!=}]]]
+operator==(const CucTim...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L50{operator==}]]]
__
+coarse : std::uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L47{coarse}]]]
+fine : std::uint64_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L48{fine}]]]
}
}
enum "PacketErrorControlMode" as C_0011113483064328568240
enum C_0011113483064328568240 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L19{PacketErrorControlMode}]] {
None
CRC16
}
package [pus] as C_0008266245607909693776 {
enum "Revision" as C_0006294303417563364908
enum C_0006294303417563364908 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L26{Revision}]] {
Unspecified
A
C
}
enum "Direction" as C_0001829865898408684403
enum C_0001829865898408684403 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L33{Direction}]] {
Unspecified
Telemetry
Telecommand
}
class "SecondaryHeader" as C_0017820635191381806822
class C_0017820635191381806822 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L20{SecondaryHeader}]] {
#SecondaryHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L51{SecondaryHeader}]]]
..
{static} #appendIdentifier(std::vector<...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L56{appendIdentifier}]]]
+getDirection() const : Direction [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L25{getDirection}]]]
+getMissionProfile() const : const MissionProfile & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L27{getMissionProfile}]]]
+getRevision() const : Revision [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L23{getRevision}]]]
+getType() const : std::string [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L29{getType}]]]
#identifierFits(std::uint32_...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L55{identifierFits}]]]
+isPusHeader() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L33{isPusHeader}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L47{loadFromConfig}]]]
+matchesMissionProfile(const Missio...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L35{matchesMissionProfile}]]]
+matchesProfile(const Missio...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L39{matchesProfile}]]]
#profileIsValid() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L52{profileIsValid}]]]
{static} #readIdentifier(const std::v...) : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L58{readIdentifier}]]]
#trailingSpareIsZero(const std::v...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L60{trailingSpareIsZero}]]]
+update(DataField * ...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L43{update}]]]
__
#m_profile : MissionProfile [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L62{m_profile}]]]
}
class "TcSecondaryHeader" as C_0004810502936549036890
class C_0004810502936549036890 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L66{TcSecondaryHeader}]] {
#TcSecondaryHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L92{TcSecondaryHeader}]]]
..
#appendTcBody(std::vector<...) const : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L96{appendTcBody}]]]
+getAcknowledgementFlags() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L69{getAcknowledgementFlags}]]]
+getServiceSubtype() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L73{getServiceSubtype}]]]
+getServiceType() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L71{getServiceType}]]]
+getSourceId() const : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L75{getSourceId}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L88{loadFromConfig}]]]
#parseTcBody(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L97{parseTcBody}]]]
+setAcknowledgementFlags(std::uint8_t...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L78{setAcknowledgementFlags}]]]
+setServiceSubtype(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L82{setServiceSubtype}]]]
+setServiceType(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L80{setServiceType}]]]
+setSourceId(std::uint32_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L84{setSourceId}]]]
#tcSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L95{tcSize}]]]
__
#m_acknowledgementFlags : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L99{m_acknowledgementFlags}]]]
#m_serviceSubtype : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L101{m_serviceSubtype}]]]
#m_serviceType : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L100{m_serviceType}]]]
#m_sourceId : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L102{m_sourceId}]]]
}
class "TmSecondaryHeader" as C_0004398363156631507099
class C_0004398363156631507099 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L106{TmSecondaryHeader}]] {
#TmSecondaryHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L132{TmSecondaryHeader}]]]
..
#appendTmTail(std::vector<...) const : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L135{appendTmTail}]]]
+getDestinationId() const : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L113{getDestinationId}]]]
+getServiceSubtype() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L111{getServiceSubtype}]]]
+getServiceType() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L109{getServiceType}]]]
+getTimestamp() const : const time::CucTime & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L115{getTimestamp}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L128{loadFromConfig}]]]
#parseTmTail(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L136{parseTmTail}]]]
+setDestinationId(std::uint32_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L122{setDestinationId}]]]
+setServiceSubtype(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L120{setServiceSubtype}]]]
+setServiceType(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L118{setServiceType}]]]
+setTimestamp(const time::...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L124{setTimestamp}]]]
#tmTailSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L137{tmTailSize}]]]
__
#m_destinationId : std::uint32_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L141{m_destinationId}]]]
#m_serviceSubtype : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L140{m_serviceSubtype}]]]
#m_serviceType : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L139{m_serviceType}]]]
#m_timestamp : time::CucTime [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L142{m_timestamp}]]]
}
package [rev_a] as C_0009768887864433069962 {
class "TcHeader" as C_0001755478337597829079
class C_0001755478337597829079 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L147{TcHeader}]] {
+TcHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L150{TcHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L155{deserialize}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L157{getSize}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L159{serialize}]]]
__
}
class "TmHeader" as C_0017247575000911418816
class C_0017247575000911418816 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L185{TmHeader}]] {
+TmHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L188{TmHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L198{deserialize}]]]
+getPacketSubcounter() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L194{getPacketSubcounter}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L200{getSize}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L206{loadFromConfig}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L202{serialize}]]]
+setPacketSubcounter(std::uint8_t...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L196{setPacketSubcounter}]]]
__
}
}
package [rev_c] as C_0012782847369517139209 {
class "TcHeader" as C_0004296692240053397319
class C_0004296692240053397319 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L166{TcHeader}]] {
+TcHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L169{TcHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L174{deserialize}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L176{getSize}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L178{serialize}]]]
__
}
class "TmHeader" as C_0009041677057813291073
class C_0009041677057813291073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L216{TmHeader}]] {
+TmHeader(MissionProfi...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L219{TmHeader}]]]
..
+deserialize(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L235{deserialize}]]]
+getMessageTypeCounter() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L227{getMessageTypeCounter}]]]
+getSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L237{getSize}]]]
+getTimeReferenceStatus() const : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L229{getTimeReferenceStatus}]]]
+loadFromConfig(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L243{loadFromConfig}]]]
+serialize() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L239{serialize}]]]
+setMessageTypeCounter(std::uint16_...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L231{setMessageTypeCounter}]]]
+setTimeReferenceStatus(std::uint8_t...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L233{setTimeReferenceStatus}]]]
__
}
}
class "SecondaryHeaderFactory" as C_0002158309051506416943
class C_0002158309051506416943 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L14{SecondaryHeaderFactory}]] {
+create(Revision rev...) const : ccsds::Result<std::shared_ptr<SecondaryHeaderAbstract>> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{create}]]]
+create(const std::s...) const : ccsds::Result<std::shared_ptr<SecondaryHeaderAbstract>> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L20{create}]]]
{static} +isPusSelector(const std::s...) : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L25{isPusSelector}]]]
+typeIsSupported(const std::s...) const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L23{typeIsSupported}]]]
__
}
}
class "MissionProfile" as C_0013482125278780870275
class C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L47{MissionProfile}]] {
__
+destinationIdOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L52{destinationIdOctets}]]]
+direction : pus::Direction [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L50{direction}]]]
+packetErrorControl : PacketErrorControlMode [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L53{packetErrorControl}]]]
+pusATmPacketSubcounterPresent : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L57{pusATmPacketSubcounterPresent}]]]
+pusEnabled : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L48{pusEnabled}]]]
+pusRevision : pus::Revision [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L49{pusRevision}]]]
+secondaryHeaderSpareOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L58{secondaryHeaderSpareOctets}]]]
+sourceIdOctets : std::uint8_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L51{sourceIdOctets}]]]
+telemetryCuc : time::CucConfiguration [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L56{telemetryCuc}]]]
+telemetryTimeCode : time::Format [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L55{telemetryTimeCode}]]]
+telemetryTimestampPresent : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L54{telemetryTimestampPresent}]]]
}
class "Result<std::shared_ptr<ccsds::SecondaryHeaderAbstract>>" as C_0007514998099265917869
class C_0007514998099265917869 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{Result}]] {
__
}
class "DataField" as C_0003434639916644007055
class C_0003434639916644007055 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L39{DataField}]] {
+DataField() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L46{DataField}]]]
+~DataField() = default : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L49{~DataField}]]]
..
+RegisterSecondaryHeader<T>() : ResultBool
+getApplicationData() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L186{getApplicationData}]]]
+getApplicationData() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L184{getApplicationData}]]]
+getApplicationDataBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L164{getApplicationDataBytesSize}]]]
+getDataFieldAbsoluteBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L161{getDataFieldAbsoluteBytesSize}]]]
+getDataFieldAvailableBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L170{getDataFieldAvailableBytesSize}]]]
+getDataFieldUsedBytesSize() const : std::uint16_t [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L167{getDataFieldUsedBytesSize}]]]
+getMissionProfile() const : const MissionProfile & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L64{getMissionProfile}]]]
+getPusSecondaryHeaderFactory() const : const pus::SecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L141{getPusSecondaryHeaderFactory}]]]
+getSecondaryHeader() const : std::shared_ptr<const SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L199{getSecondaryHeader}]]]
+getSecondaryHeader() : std::shared_ptr<SecondaryHeaderAbstract> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L197{getSecondaryHeader}]]]
+getSecondaryHeaderAutoUpdateStatus() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L189{getSecondaryHeaderAutoUpdateStatus}]]]
+getSecondaryHeaderBytes() : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L173{getSecondaryHeaderBytes}]]]
+getSecondaryHeaderBytes() const : std::vector<std::uint8_t> [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L175{getSecondaryHeaderBytes}]]]
+getSecondaryHeaderFactory() : SecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L134{getSecondaryHeaderFactory}]]]
+getSecondaryHeaderFactory() const : const SecondaryHeaderFactory & [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L136{getSecondaryHeaderFactory}]]]
+getSecondaryHeaderFlag() const : bool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L194{getSecondaryHeaderFlag}]]]
+serialize() : ResultBuffer [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L181{serialize}]]]
+setApplicationData(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L79{setApplicationData}]]]
+setApplicationData(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L71{setApplicationData}]]]
+setDataPacketSize(const std::u...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L150{setDataPacketSize}]]]
+setMissionProfile(const Missio...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L63{setMissionProfile}]]]
+setSecondaryHeader(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L98{setSecondaryHeader}]]]
+setSecondaryHeader(const ccsds:...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L123{setSecondaryHeader}]]]
+setSecondaryHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L108{setSecondaryHeader}]]]
+setSecondaryHeader(const std::v...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L116{setSecondaryHeader}]]]
+setSecondaryHeader(const std::u...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L88{setSecondaryHeader}]]]
+setSecondaryHeader(std::shared_...) : ResultBool [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L131{setSecondaryHeader}]]]
+setSecondaryHeaderAutoUpdateStatus(const bool e...) : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L156{setSecondaryHeaderAutoUpdateStatus}]]]
+update() : void [[[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L205{update}]]]
__
}
class "Packet" as C_0013265662939920414927
class C_0013265662939920414927 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L208{Packet}]] {
__
}
}
C_0017566881135794494958 o-- C_0009051388942408461891 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L67{m_code}]] : -m_code
C_0008099319371458986879 o-- C_0017566881135794494958 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSResult.h#L92{data}]] : -data
C_0008186123745702387052 ..|> C_0008099319371458986879
C_0016810538617857061367 ..|> C_0008099319371458986879
C_0018286355310635740643 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L43{}]]
C_0018286355310635740643 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L43{}]]
C_0018286355310635740643 ..> C_0016810538617857061367 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSConfig.h#L86{}]]
C_0005445694194400424073 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L64{}]]
C_0005445694194400424073 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L64{}]]
C_0005445694194400424073 ..> C_0003434639916644007055 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L71{}]]
C_0005445694194400424073 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L95{}]]
C_0005445694194400424073 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L105{}]]
C_0014736019873459950331 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L145{}]]
C_0014736019873459950331 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L145{}]]
C_0014736019873459950331 ..> C_0003434639916644007055 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L165{}]]
C_0014736019873459950331 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderAbstract.h#L171{}]]
C_0005445694194400424073 <|-- C_0014736019873459950331
C_0009041847757797157790 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L34{}]]
C_0009041847757797157790 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L34{}]]
C_0009041847757797157790 ..> C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L47{}]]
C_0009041847757797157790 ..> C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSSecondaryHeaderFactory.h#L57{m_creators}]] : -m_creators
C_0010465517018640617180 o-- C_0011169860713497893350 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L39{epoch}]] : +epoch
C_0010465517018640617180 o-- C_0003117097434587954110 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSTime.h#L40{pField}]] : +pField
C_0017820635191381806822 ..> C_0006294303417563364908 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L23{}]]
C_0017820635191381806822 ..> C_0001829865898408684403 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L25{}]]
C_0017820635191381806822 ..> C_0003434639916644007055 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L43{}]]
C_0017820635191381806822 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L47{}]]
C_0017820635191381806822 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L47{}]]
C_0017820635191381806822 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L47{}]]
C_0017820635191381806822 o-- C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L62{m_profile}]] : #m_profile
C_0005445694194400424073 <|-- C_0017820635191381806822
C_0004810502936549036890 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L78{}]]
C_0004810502936549036890 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L78{}]]
C_0004810502936549036890 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L88{}]]
C_0004810502936549036890 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L92{}]]
C_0017820635191381806822 <|-- C_0004810502936549036890
C_0004398363156631507099 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L122{}]]
C_0004398363156631507099 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L122{}]]
C_0004398363156631507099 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L128{}]]
C_0004398363156631507099 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L132{}]]
C_0004398363156631507099 o-- C_0014692306963991656514 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L142{m_timestamp}]] : #m_timestamp
C_0017820635191381806822 <|-- C_0004398363156631507099
C_0001755478337597829079 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L150{}]]
C_0001755478337597829079 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L155{}]]
C_0001755478337597829079 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L155{}]]
C_0004810502936549036890 <|-- C_0001755478337597829079
C_0017247575000911418816 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L188{}]]
C_0017247575000911418816 ..> C_0014692306963991656514 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L192{}]]
C_0017247575000911418816 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L198{}]]
C_0017247575000911418816 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L198{}]]
C_0017247575000911418816 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L206{}]]
C_0004398363156631507099 <|-- C_0017247575000911418816
C_0004296692240053397319 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L169{}]]
C_0004296692240053397319 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L174{}]]
C_0004296692240053397319 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L174{}]]
C_0004810502936549036890 <|-- C_0004296692240053397319
C_0009041677057813291073 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L219{}]]
C_0009041677057813291073 ..> C_0014692306963991656514 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L225{}]]
C_0009041677057813291073 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L233{}]]
C_0009041677057813291073 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L233{}]]
C_0009041677057813291073 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaders.h#L243{}]]
C_0004398363156631507099 <|-- C_0009041677057813291073
C_0002158309051506416943 ..> C_0006294303417563364908 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L18{}]]
C_0002158309051506416943 ..> C_0001829865898408684403 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L18{}]]
C_0002158309051506416943 ..> C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L18{}]]
C_0002158309051506416943 ..> C_0007514998099265917869 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{}]]
C_0002158309051506416943 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{}]]
C_0002158309051506416943 ..> C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/PusSecondaryHeaderFactory.h#L17{}]]
C_0013482125278780870275 o-- C_0006294303417563364908 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L49{pusRevision}]] : +pusRevision
C_0013482125278780870275 o-- C_0001829865898408684403 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L50{direction}]] : +direction
C_0013482125278780870275 o-- C_0011113483064328568240 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L53{packetErrorControl}]] : +packetErrorControl
C_0013482125278780870275 o-- C_0014027148995399468784 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L55{telemetryTimeCode}]] : +telemetryTimeCode
C_0013482125278780870275 o-- C_0010465517018640617180 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSMissionProfile.h#L56{telemetryCuc}]] : +telemetryCuc
C_0007514998099265917869 ..|> C_0008099319371458986879
C_0003434639916644007055 ..> C_0008186123745702387052 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L63{}]]
C_0003434639916644007055 ..> C_0008099319371458986879 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L63{}]]
C_0003434639916644007055 ..> C_0018286355310635740643 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L123{}]]
C_0003434639916644007055 ..> C_0016810538617857061367 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L181{}]]
C_0003434639916644007055 --> C_0005445694194400424073 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L211{m_secondaryHeader}]] : -m_secondaryHeader
C_0003434639916644007055 o-- C_0009041847757797157790 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L212{m_secondaryHeaderFactory}]] : -m_secondaryHeaderFactory
C_0003434639916644007055 o-- C_0002158309051506416943 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L213{m_pusSecondaryHeaderFactory}]] : -m_pusSecondaryHeaderFactory
C_0003434639916644007055 o-- C_0013482125278780870275 [[https://github.com/ExoSpaceLabs/CCSDSPack/blob/develop/inc/CCSDSDataField.h#L214{m_missionProfile}]] : -m_missionProfile
C_0003434639916644007055 <.. C_0013265662939920414927 : +<<friend>>

'Generated with clang-uml, version 0.6.3-59-gdfa2271
'LLVM version Ubuntu clang version 17.0.6 (9ubuntu1)
@enduml
