name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y cmake make g++ 

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          choco install mingw -y
          
      - name: Run build
        if: runner.os == 'Linux'
        run: |
          mkdir build && cd build && cmake .. && make

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build && cd build && cmake -G "MinGW Makefiles" ..
          
      - name: Build project (Windows)
        if: runner.os == 'Windows'
        run: |
          cd build
          cmake --build . -- 

      - name: Verify build artifacts
        if: runner.os == 'Linux'
        run: |
          ls -l lib/
          ls -l bin/

      - name: Verify build artifacts
        if: runner.os == 'Windows'
        run: |
          echo "Listing contents of build/lib/"
          Get-ChildItem -Path build/lib/
          echo "Listing contents of build/bin/"
          Get-ChildItem -Path build/bin/   

      - name: Run tests Linux
        if: runner.os == 'Linux'
        run: ./bin/CCSDSPack_tester     

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "Running CCSDSPack_tester.exe from build/bin/"
          ./build/bin/CCSDSPack_tester.exe
        shell: bash
