name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake make g++ 

      - name: Run build script
        run: |
          cmake
          make

      - name: Verify build artifacts
        run: |
          ls -l lib/
          ls -l bin/

      - name: Run tests
        run: ./bin/CCSDSPack_tester

