name: Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          choco install mingw -y

      - name: Configure CMake
        run: |
          cd build && cmake -G "MinGW Makefiles" ..
          
      - name: Build project
        run: |
          cd build
          cmake --build . -- 

      - name: Verify build artifacts
        run: |
          echo "Listing contents of build/lib/"
          Get-ChildItem -Path build/lib/
          echo "Listing contents of build/bin/"
          Get-ChildItem -Path build/bin/      

      - name: Run tests
        run: |
          echo "Running CCSDSPack_tester.exe from build/bin/"
          cd build/bin && ./CCSDSPack_tester.exe
        shell: bash
